Revert "Remove unused content_icon and content_meta_type properties from FTI."
This reverts commit da5b2f5f8770eb3683974e9a0db0ab79e56933b3.

I looked at `plone.app.contenttypes` for comparison, but those are Dexterity FTIs, and here we have an old-style FTI.
When I locally added `icon_expr` in here, I actually got an error while adding a Plone Site:

```
ValueError: http://localhost:8080/@@plone-addsite
Traceback (innermost last):
  Module ZPublisher.WSGIPublisher, line 181, in transaction_pubevents
  Module ZPublisher.WSGIPublisher, line 391, in publish_module
  Module ZPublisher.WSGIPublisher, line 285, in publish
  Module ZPublisher.mapply, line 98, in mapply
  Module ZPublisher.WSGIPublisher, line 68, in call_object
  Module Products.CMFPlone.browser.admin, line 299, in __call__
  Module Products.CMFPlone.factory, line 165, in addPloneSite
  Module Products.GenericSetup.tool, line 393, in runAllImportStepsFromProfile
   - __traceback_info__: profile-Products.CMFPlone:plone
  Module Products.GenericSetup.tool, line 1513, in _runImportStepsFromContext
  Module Products.GenericSetup.tool, line 1360, in _doRunHandler
  Module Products.CMFPlone.setuphandlers, line 139, in importFinalSteps
  Module Products.GenericSetup.tool, line 393, in runAllImportStepsFromProfile
   - __traceback_info__: profile-Products.CMFPlone:dependencies
  Module Products.GenericSetup.tool, line 1504, in _runImportStepsFromContext
  Module Products.GenericSetup.tool, line 1316, in _doRunImportStep
   - __traceback_info__: typeinfo
  Module Products.CMFCore.exportimport.typeinfo, line 222, in importTypesTool
  Module Products.GenericSetup.utils, line 926, in importObjects
   - __traceback_info__: portal_types
  Module Products.GenericSetup.utils, line 922, in importObjects
   - __traceback_info__: types/Discussion_Item
  Module Products.GenericSetup.utils, line 525, in _importBody
  Module Products.CMFCore.exportimport.typeinfo, line 61, in _importNode
  Module Products.GenericSetup.utils, line 757, in _initProperties
ValueError: undefined property 'content_icon'
```

So let's keep the old-style properties, although I am not sure they are actually used anywhere in current Plone.